import './theme-chalk/coast.scss';
export { default as CoSwitch } from './switch/Switch.vue';
export { default as CoButton } from './button/Button.vue';
export { default as CoButtonGroup } from './button/ButtonGroup.vue';
export { default as CoTabs } from './tabs/Tabs.vue';
export { default as CoTabPanel } from './tabs/TabPanel.vue';
export { default as CoDialog } from './dialog/Dialog.vue';
export { default as CoCard } from './card/Card.vue';
export { default as CoIcon } from './icon/Icon.vue';
export { default as CoInput } from './input/Input.vue';
export { openDialog as openDialog } from './dialog/openDialog';
