export { default as CoSwitch } from './Switch.vue';
export { default as CoButton } from './button/Button.vue';
export { default as CoButtonGroup } from './button/ButtonGroup.vue';
export { default as CoTabs } from './Tabs.vue';
export { default as CoTabPanel } from './TabPanel.vue';
export { default as CoDialog } from './Dialog.vue';
export { default as CoCard } from './Card.vue';
export { default as CoIcon } from './icon/Icon.vue';
export { openDialog as openDialog } from './openDialog';
