name: Publish to NPM registry

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test:lib

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          registry-url: https://registry.npmjs.com/
      - name: Install dependencies
        run: yarn install
      - name: build
        run: yarn build:lib
      - name: Publish npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}