name: Unit Test

on:
  push:
    branches:
      - feature/github-actions
    paths:
      - 'lib'

jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn install
      - name: Test lib
        run: yarn test:lib

