name: Unit Test

on:
  push:
    branches:
      - 'feature/test-coverage-action'
    paths:
      - 'lib/**'
      - 'package.json'

jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn install
      - name: Test lib
        run: yarn test:lib
      - name: Generate coverage report
        run: yarn coverage:lib
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/clover.xml
          flags: unit-tests
          name: coast-ui-vue3
          fail_ci_if_error: true